version: "3"

services:
  orders:
    image: orders-and-payments/orders:${TAG:-latest}
    build:
      context: ./services/orders
      dockerfile: Dockerfile
    ports:
      - '8000:8000'
    depends_on:
      - redis
      

  payments:
    image: orders-and-payments/payments:${TAG:-latest}
    build:
      context: ./services/payments
      dockerfile: Dockerfile
    ports:
      - "8001:8001"

  clients:
    image: orders-and-payments/clients:${TAG:-latest}
    build:
      context: ./clients
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    
  redis:
    image: "bitnami/redis:latest"
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL
    labels:
      kompose.service.type: nodeport
    ports:
      - "6379:6379"
    volumes:
      - "redis_data:/bitnami/redis"